[build]
  command = "npx prisma generate && npx prisma migrate deploy && npm run build"

[build.environment]
  NODE_VERSION = "18"
  NEXT_TELEMETRY_DISABLED = "1"

[[plugins]]
  package = "@netlify/plugin-nextjs"

